plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.beyond'
version = '0.0.1-SNAPSHOT'
description = 'basic project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

//gradle 빌드툴을 사용하더라도 저장소로 maven repository를 사용
repositories {
	mavenCentral()
}

//의존성(dependenciy) : 해당 프로젝트에서 사용할 라이브러리
dependencies {
//    spring 웹서비스(http)를 위한 기본 의존성
	implementation 'org.springframework.boot:spring-boot-starter-web'
//    getter, setter등 개발의 편의성을 증대시켜주는 각종 어노테이션을 포함하는 의존성(=lombok)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

//    스프링에서 화면을 만들어 사용자에게 주는 mvc기술 중 하나
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

//    아래는 테스트코드 작성을 위한 의존성
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
